config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'about' => 'homes#about'

  resources :users

  resources :sales
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :user

  validates :quota, presence: true, numericality: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :sales, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { minimum: 2 }
  validates :introduction, length: { maximum: 100 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/sample_chara.jpeg")
      profile_image.attach(io: File.open(file_path),filename: 'default-image-jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!, except: [:top]

  def top
  end

  def about
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)
    @sale.user_id = current_user.id
    if @sale.save
      flash[:notice] = 'ノルマ達成に向けて頑張ろう！'
      redirect_to sales_path
    else
      flash[:notice] = "ノルマ設定に失敗しました"
      render 'new'
    end
  end

  def index
    @sales = Sale.all
    @sales_achievement_rate = (500000 / @sales.count) * 100
  end

  def show
  end

  def edit
  end

  private

  def sale_params
    params.require(:sale).permit(:quota, :title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :paramsid_set, only: [:show, :edit, :update]

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "情報の編集が完了しました"
      redirect_to user_path(@user)
    else
      flash[:notice] = "情報の編集に失敗しました"
      redirect_to request.referer
    end

  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def paramsid_set
     @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="container">
  <div class="bg-dark d-flex align-items-center justify-content-center animation-area">
      <h1>ようこそ「ノルマスター」へ🏃💨</h1>
      <!--今月のノルマ入力していない場合のみnewvewsへ遷移させたい-->
      <h2><%= link_to 'Start',new_sale_path %></h2>
  </div>

  <%= javascript_pack_tag 'anime.js' %>
  <script>
    const animationArea = document.querySelector(".animation-area");

    for (let i = 0; i <= 50;  i++) {
      const blocks = document.createElement("div");
       blocks.classList.add("block");
       animationArea.appendChild(blocks);
     }

      function animateBlocks() {
        anime({
          targets: ".blocks",
          translateX: function() {
            return anime.random(-800, 700);
          }
        });
      }

     animateBlocks();


  </script>

  <div class="mx-auto">
    <%= link_to 'ログアウト',destroy_user_session_path, method: :delete, class: "text-center" %>
  </div>

  <div class="mx-auto">
    <%= link_to 'ユーザー編集',edit_user_path(current_user.id), class: "text-center" %>
  </div>

  <div class="mx-auto">
    <%= link_to 'マイページ',user_path(current_user.id), class: "text-center" %>
  </div>



</div>

app/views/homes/top.html.erb
<div class="container">

  <div class="row mx-auto mt-5 mb-5">
    <h1>トップ画面</h1>
  </div>

  <div class="row">
    <div class="col-md-8 mx-auto">
      <%= link_to '新規登録',new_user_registration_path %>
      <%= link_to 'ログイン',user_session_path, method: :post %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=DotGothic16&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= flash[:notice] %>
  <header>
   <nav class="navbar navbar-expand-lg bg-dark pt-3 pb-3 text-center">
     <div class="collapse navbar-collapse">
       <div class="navber navber-brand col-md-4"><%= link_to 'ノルマスター', root_path %></div>
        <ul class="navbar-nav mx-auto">
          <% if user_signed_in? %>
          <li class="nav-item ml-5">
            <%= link_to "ミニゲーム",about_path ,class: "nav-link" %>
          </li>
          <li class="nav-item ml-5">
           <%= link_to "ノルマ設定",new_sale_path ,class: "nav-link" %>
          </li>
          <li class="nav-item ml-5">
            <%= link_to "ログアウト",destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item ml-5">
            <%= link_to "ゲストログイン", class: "nav-link" %>
          </li>
          <li class="nav-item ml-5">
            <%= link_to "新規登録",new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item ml-5">
            <%= link_to "ログイン",user_session_path, method: :post,  class: "nav-link" %>
          </li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <%= link_to user_path(current_user.id) do %>
           <%= image_tag current_user.get_profile_image(50,50), class: "header-image mr-3" %>
          <% end %>
        <% end %>
      </div>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>

app/views/sales/edit.html.erb
<h1>Sales#edit</h1>
<p>Find me in app/views/sales/edit.html.erb</p>

app/views/sales/index.html.erb
<div class="text-center">
 <div class="mt-3 mb-3">
 <h1>みんなのノルマ</h1>
</div>

<div class="card-container">
<% @sales.each do |s| %>
<div class="card" style="width: 18rem;">
  <% if s.title == "ちょろいな" %>
   <%= image_tag '怪物くん.jpg', size: "50%x50%" %>
  <% elsif s.title == "まあまあだな" %>
   <%= image_tag '鬼.jpg', size: "50%x50%" %>
  <% elsif s.title == "いつも通りだ" %>
   <%= image_tag 'golira.jpeg', size: "50%x50%" %>
  <% elsif s.title == "ちょっと高くね？" %>
   <%= image_tag 'タコ.jpg', size: "50%x50%" %>
  <% else %>
   <%= image_tag '魔王.jpg', size: "50%x50%" %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= s.user.name %></h5>
    <p class="card-text"><%= s.body %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">ノルマ：<%= s.quota %></li>
    <li class="list-group-item">達成率：<%= (5000000 / s.quota) * 100 %> %</li>
    <li class="list-group-item">A third item</li>
  </ul>
  <div class="card-body">
    <%= link_to '編集', edit_sale_path(s.id), class: "card-link" %>
    <%= link_to '編集', edit_sale_path(s.id), class: "card-link" %>
  </div>
</div>
<% end %>
</div>

</div>

app/views/sales/new.html.erb
<div class="container mt-5">
  <div class="mx-auto mb-5 text-center">
    <h1>ノルマ情報入力画面</h1><br>
    <%= link_to 'みんなのノルマ', sales_path %>
  </div>

    <%= form_with model: @sale do |f| %>

     <div class="row mb-3 form_group">
      <label class="col-md-2 col-form-label"><strong>月間ノルマ</strong></label>
      <div class="col-md-10"><%= f.number_field :quota, class: "form_control" %></div>
      <p>※全て数値で入力してください<br>
         例（5,000,000）</p>
     </div>

     <div class="row mb-3 form_group">
      <label class="col-md-2 col-form-label"><strong>ノルマにする所感</strong></label>
      <div class="col-md-10"><%= f.select :title, [["ちょろいな","ちょろいな"], ["まあまあだな","まあまあだな"], ["いつも通りだ", "いつも通りだ"], ["ちょっと高くね？","ちょっと高くね？"], ["高すぎだわ！","高すぎだわ！"]], include_blank: "選択して下さい" %></div>
     </div>

     <div class="row mb-3 form_group">
      <label class="col-md-2 col-form-label"><strong>意気込み🔥</strong></label>
      <div class="col-md-10"><%= f.text_area :body, :size=>"30x5", placeholder: "例）今月は絶対に達成するぞ！！", class: "form_control" %></div>
     </div>

     <div class="form_group text-center">
      <%= f.submit '設定完了', class: "btn btn-success btn-sm" %>
     </div>

    <% end %>
  </div>


</div>

app/views/sales/show.html.erb
<h1>Sales#show</h1>
<p>Find me in app/views/sales/show.html.erb</p>

app/views/users/edit.html.erb
<div class="container mt-5">
  <div class="mx-auto mb-5 mypage-top">
    <h1>ユーザー編集</h1><br>
    <%= link_to user_path(@user.id) do %>
     <%= image_tag @user.get_profile_image(100,100), class: "profile_image" %>
    <% end %>
  </div>

  <div class="user_detil mx-auto">
    <%= form_with model: @user do |f| %>

     <div class="row mb-3 form_group">
      <label class="col-md-2 col-form-label">画像</label>
      <div class="col-md-10"><%= f.file_field :profile_image, class: "form_control" %></div>
     </div>

     <div class="row mb-3 form_group">
      <label class="col-md-2 col-form-label">名前</label>
      <div class="col-md-10"><%= f.text_field :name, :size=>"30",  class: "form_control" %></div>
     </div>

     <div class="row mb-3 form_group">
      <label class="col-md-2 col-form-label">説明</label>
      <div class="col-md-10"><%= f.text_area :introduction, :size=>"30x5", class: "form_control" %></div>
     </div>

     <div class="form_group text-center">
      <%= f.submit 'アップデート', class: "btn btn-info btn-sm" %>
     </div>

    <% end %>
  </div>

  <div class="mx-auto mt-5 text-center">
    <p>トップページは<%= link_to 'こちら', root_path %></p>
  </div>


</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="mx-auto mb-3 mypage-top">
    <h1>マイページ</h1>
  </div>

  <div class="mx-auto mb-5">
    <p>編集は<%= link_to 'こちら', edit_user_path(current_user.id) %></p>
    <p>フォロー：</p>
    <p>フォロワー：</p>
  </div>

  <div class="row mx-auto">
   <div class="col-md-4">
     <h4><%= @user.name %>さんのプロフィール画像</h4>
     <%= image_tag @user.get_profile_image(300,300), class: "profile_image" %>
   </div>
   <div class="col-md-8">
     <table class="table">
       <thead>
         <tr>
           <th>名前</th>
           <th>自己紹介</th>
         </tr>
       </thead>
       <tbody>
         <tr>
           <td><%= @user.name %></td>
           <td><%= @user.introduction %></td>
         </tr>
       </tbody>
     </table>
   </div>
  </div>


</div>